[project]
name = "qrcode-generator"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "colorama>=0.4.6",
    "eel>=0.18.1",
    "pillow>=11.1.0",
    "pypng>=0.20220715.0",
    "pyqrcode>=1.2.1",
    "rich>=13.9.4",
]
